-- Row-level security: every user-owned table is filtered (and write-guarded) by owner.
-- dbo.users is filter-only so sign-up can run through a privileged (db_owner) path.
CREATE SECURITY POLICY [sec].[user_isolation_policy]
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([id]) ON [dbo].[users],
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habit_logs],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habit_logs] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habit_logs] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habits],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habits] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[habits] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[weekly_routines],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[weekly_routines] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[weekly_routines] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[personal_records],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[personal_records] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[personal_records] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[body_metrics],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[body_metrics] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[body_metrics] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[water_intake],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[water_intake] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[water_intake] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[workouts],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[workouts] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[workouts] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[substance_logs],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[substance_logs] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[substance_logs] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[sleep_logs],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[sleep_logs] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[sleep_logs] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[symptom_logs],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[symptom_logs] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[symptom_logs] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[bills],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[bills] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[bills] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[meals],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[meals] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [body].[meals] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[earnings],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[earnings] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[earnings] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[expenses],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[expenses] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[expenses] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[investments],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[investments] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [finance].[investments] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[meditation_sessions],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[meditation_sessions] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[meditation_sessions] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[budgets],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[budgets] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[budgets] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[journal_entries],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[journal_entries] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [mind].[journal_entries] AFTER UPDATE,
    ADD FILTER PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[goals],
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[goals] AFTER INSERT,
    ADD BLOCK PREDICATE [sec].[fn_user_access_predicate]([user_id]) ON [plan].[goals] AFTER UPDATE
WITH (STATE = ON, SCHEMABINDING = ON);
GO

